Repository AdaSupport/documentation, pull requests merged in 2021-08, with the labels that each got.

#21 update version to 1.3.9
  source/includes/_android.md.erb
Labels: size/XS

#22 Add docs for `sensitiveMetaFields`
  source/includes/_embed2.md.erb
Labels: size/M

#24 ANE-380: mask ids in examples
  source/includes/data_api.md.erb
Labels: size/S
