Repository AdaSupport/documentation, pull requests merged in 2021-04, with the labels that each got.

#10 Add documentation for Ada Engage functions
  README.md
  source/includes/_embed2.md.erb
Labels: size/L

#11 Update deploy script command
  README.md
Labels: size/XS

#12 SUP-447: Updating docs and a bugfix for sections
  source/includes/_android.md.erb
  source/includes/_ios.md.erb
  source/stylesheets/screen.css.scss
Labels: size/S

#13 SUP-447: maven address change
  source/includes/_android.md.erb
Labels: size/XS

#14 SUP-447: Updating 1 incorrect url
  source/includes/_android.md.erb
Labels: size/XS

#15 Remove preload documentation
  source/includes/_embed2.md.erb
Labels: size/XS
